export const filterData = [
  {
    name: 'Color',
    id: 123111,
    type: 1,
    icon: '',
    childs: [
      {
        name: '14K',
        id: 123112,
        type: 2,
        icon: '',
        childs: [],
      },
      {
        name: '香槟金',
        id: 123113,
        type: 2,
        icon: '',
        childs: [],
      },
      {
        name: '14K 分色',
        id: 123114,
        type: 2,
        icon: '',
        childs: [],
      },
      {
        name: '香槟金分色',
        id: 123115,
        type: 2,
        icon: '',
        childs: [],
      },
      {
        name: '三色',
        id: 123116,
        type: 2,
        icon: '',
        childs: [],
      },
      {
        name: '白金色',
        id: 123117,
        type: 2,
        icon: '',
        childs: [],
      },
      {
        name: '18K',
        id: 123118,
        type: 2,
        icon: '',
        childs: [],
      },
    ],
  },
  {
    name: 'Design',
    type: 1,
    id: 123120,
    icon: '',
    childs: [
      {
        name: '古巴链',
        icon: '',
        id: 123121,
        type: 2,
        childs: [],
      },
      {
        name: '蛇身链',
        icon: '',
        id: 123122,
        type: 2,
        childs: [],
      },
      {
        name: '绳链',
        icon: '',
        id: 123123,
        type: 2,
        childs: [],
      },
      {
        name: '珠珠链',
        icon: '',
        id: 123124,
        type: 2,
        childs: [],
      },
    ],
  },
  // {
  //   name: 'LENGTH',
  //   type: 1,
  //   icon: '',
  //   id: 123128,
  //   childs: [
  //     {
  //       name: '10CM',
  //       icon: '',
  //       type: 2,
  //       id: 123129,
  //       childs: [],
  //     },
  //     {
  //       name: '20CM',
  //       icon: '',
  //       type: 2,
  //       id: 123130,
  //       childs: [],
  //     },
  //     {
  //       name: '30CM',
  //       icon: '',
  //       type: 2,
  //       id: 123131,
  //       childs: [],
  //     },
  //   ],
  // },
]
